### PR TITLE
Fix #4 build documentation

### LINKED ISSUE #4: Build documentation fail
```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Ejecutando Sphinx v4.5.0

Configuration error:
Hay un error programable en su archivo de configuración:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/fraya/Dylan/objc-dylan/documentation/source/conf.py", line 15, in <module>
    import sphinxcontrib.dylan.themes as dylan_themes
ModuleNotFoundError: No module named 'sphinxcontrib.dylan'
```

### PR DESCRIPTION
**Pull request by fraya**
- Add submodule `sphinx-extensions`
- Include module in `conf.py`

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
it doesn't seem like the right thing to do is to have to include sphinx-extensions into every single project...

**Comment by fraya** [comment]
I'm trying to add Github Actions to Opendylan's website repo and execute the `update` script. It recursively checkout the libraries and make the documentation. The process fails and I saw that the http library is ok and use this way. What solution do you suggest to solve it?

**Comment by waywardmonkeys** [comment]
Maybe a custom step in the GitHub actions that installs and sets up the stuff for building docs. Can do it as part of process of setting up Dylan itself perhaps.

**Comment by fraya** [comment]
Right now [I install Sphinx](https://github.com/fraya/website/blob/master/.github/workflows/build-and-test.yml). If all the libraries had the same path to find `sphinx-extensions` in `conf.py` it would not be necessary to include the submodule in each one.

**Comment by waywardmonkeys** [comment]
Maybe put it in the `PYTHONPATH` env variable…

**Comment by fraya** [comment]
I [tried](https://github.com/fraya/website/blob/f1139ff1f93f68aa7b0938100058a38b71b615c3/.github/workflows/build-and-test.yml#L39) but I must have done something wrong. Thank you, I'll think about it.

**Pull request closed without merging**
